### ISSUE TITLE
Archive/deprecate this package?

### ISSUE THREAD

**Issue by daleyjem** [enzymejs/enzyme#2610]
If there are not plans to maintain this package and its dependencies, how about it be Github-archived and NPM-deprecated?

**Comment by ljharb** [comment]
The package and its deps are maintained currently, and either way, that would be up to its maintainers, and not something that would _ever_ be appropriate to file an issue for on any project.

**Comment by daleyjem** [comment]
> The package and its deps are maintained currently, and either way, that would be up to its maintainers, and not something that would _ever_ be appropriate to file an issue for on any project.

Sorry, but I believe it absolutely _is_ appropriate to request NPM deprecation for something that [hasn't published to NPM in 5 years](https://www.npmjs.com/package/enzyme).

**Comment by ljharb** [comment]
Unfortunately your belief is incorrect, and since you're not a maintainer of this package, also irrelevant.

Publish recency isn't relevant, and all the subpackages have been published much more recently. Maintenance can't be measured solely by publish dates.

**Comment by daleyjem** [comment]
> Publish recency isn't relevant

Well now that just sounds obtuse.

Do you know then of enzyme's future maintenance plans and/or roadmap?

**Comment by ljharb** [comment]
The roadmap is the same it’s always been; catchup to latest React support and fix bugs.

I’ve however been a volunteer solo maintainer on the project for 6-7 years, with very few contributions (code, financial, or otherwise), and that makes it hard to provide the free service of open source maintenance in a timely fashion.

**Comment by daleyjem** [comment]
Respectfully, if every honest question that comes into this repo is met with a message of "irrelevance", I wouldn't expect that situation to improve.

From your docs:
![image](https://github.com/user-attachments/assets/ed03c5db-b58c-46f8-b2cb-20db7d008c9d)

`enzyme` simply registers as having a poor maintenance score, and "enzyme react dead" in a Google search has no shortage of articles... so I thought to inquire.

If you plan on maintaining it further, that's certainly sufficient. Thanks.

**Comment by ljharb** [comment]
Sure, did you have a specific feature or desired support? Do open an issue about that! This isn't one of those, and it's not an honest question, because it's based on an objectively false presumption (`If there are not plans to maintain this package and its dependencies`). An honest question would have asked what the plans for that ARE, instead of jumping to a solution for a nonexistent problem.

"poor maintenance score" presumes that any such score is _possible_ to be broadly useful, vs being wildly inaccurate. I'm certainly aware that folks have made claims that enzyme is "dead", but hopefully one learns not to trust every claim made on the internet.

**Comment by daleyjem** [comment]
I'm not sure what tone you read the original post in, but it seemed to put you on edge.

It's fine, man. Thanks for the response. Good luck.
